@host = http://localhost
@port = 5037
@Restaurants_API_HostAddress = {{host}}:{{port}}

GET {{Restaurants_API_HostAddress}}/api/weatherforecast/23/example?max=15
Accept: application/json
Guid: {{$guid}}
LocalDate:{{$datetime iso8601}}
Random-int: {{$randomInt}}

###

POST {{Restaurants_API_HostAddress}}/api/weatherforecast/generate?count=5
Content-Type: application/json

{
    "min": -23,
    "max": 23
}

